### ISSUE TITLE
_ Roadmap _ - LS

### ISSUE THREAD

**Issue by PRG-James** [TheWalkingZed/TWZ-Issue-Tracker#25]
Road Map:

- [x] Fix zombie issues in current game - NULL REFF
- [x] Nerf ranged zombies block damage. - Nerf hard.
- [ ] Work on the reward mod so we can get our Loyalty Gems and Warrior Medals back in game. Ticket: #27 
- [ ] Add Loyalty Gems to vote reward and notice to the players. Ticket: #27 
- [ ] Add Hellbeast Ticket: #24 
- [ ] #28
- [x] #29
- [ ] Begin planning the TWZ_Armor_Mod. There are several aspects we have to work out. Login buff + dawning of the gear = applied buff / We have to do light and heavy, balanced, and also miner gear, and cloth crafters gear for level 6 crafting, etc etc etc. The armor mod will be a big one. We just need to get to that point.
- [ ] TWZ_Custom_Weapons will come after. 

**Near Term**

- [x] Boss zombies
- [ ] Boss drops
- [ ] Boss gear
- [ ] Boss weapons
- [ ] Boss admin POI / Shrine (I will provide the details)
- [ ] Boss Crafting Station - A coffin

**Long Term**

- [ ] Printing station - Location for players to print info books about the mod, to include Skill point books, Knowledge books, etc. Also the location of ink, pen, etc.
- [ ] Info TVs - A set of easy to craft televisions, which display core info about our servers. They can be placed in the lobby and also player houses.
- [ ] Thors Hammer - Special and difficult boss weapon. While held, player is immune to shock damage. Hammer engulfs the player with electricity. When the player jumps, they can cover a significant amount of distance with no fall damage. Upon landing, massive electrical storm under feet and push AOE outward. Heavy knockback and heavy damage.
- [ ] Add Perk - Dungeon Runner - a series of perks that a player  can invest in that raise 1 stat while lowering another. Increase tank and decrease damage, etc.
- [ ] Winestation - Drink perks outside of the drinking machine. Drink = Buff
- [ ] Tek Power mod - Tek power, light up suits, players can fly - lots of dreamy stuff in this one.
- [ ] Virtual Backpack - Backpack space that is not on the player, but a small, universal, backpack. The purpose is so that when a player is full, and they really need that 1 extra slot, we can allow it.

**From here - Let creativity flow!**
